version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${spring.datasource.username}
      POSTGRES_DB: ${spring.datasource.name}
      POSTGRES_PASSWORD: ${spring.datasource.password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: ${spring.datasource.username}
      DB_NAME: ${spring.datasource.name}
      DB_PASSWORD: ${spring.datasource.password}
    restart: always

volumes:
  postgres-data: