version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
#
#  nginx:
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - app
#    restart: always

volumes:
  postgres-data: