spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  mail:
   host: smtp.gmail.com
   port: 587
   username: ${spring.mail.username}
   password: ${spring.mail.password}
   properties:
    mail:
     smtp:
      auth: true
      starttls:
        enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html